#!/bin/bash

#SBATCH -N 1-1 -n 1 
#SBATCH -p gpu --gres=gpu:1
#SBATCH --account=carney-tserre-condo
#SBATCH --mem=40gb
#SBATCH -t 20:00:00
 
source /gpfs/data/epavlick/mlepori/miniconda3/etc/profile.d/conda.sh

conda activate relational-circuits
python $PROJECT_DIR/linear_probe_intervention.py --pretrain $MODEL --run_id $RUN_ID --patch_size $PATCH_SIZE --compositional $COMPOSITIONAL --control $CONTROL --alpha $ALPHA --obj_size $OBJ_SIZE
