pretrain: "imagenet"
patch_size: "32"
device: "cuda"

im_path_same: "stimuli/patching/1-25/same.png"
im_path_diff: "stimuli/patching/1-25/different.png"
im_path_corrupt: "stimuli/patching/1-25/shape.png"


outpath: "Results/Tracing/Imagent/1-25/shape"