pretrain: "imagenet"
patch_size: "32"
device: "cuda"

im_path_same: "stimuli/patching/15-3/same.png"
im_path_diff: "stimuli/patching/15-3/different.png"
im_path_corrupt: "stimuli/patching/15-3/texture.png"


outpath: "Results/Patching/Imagent/15-3/texture"