pretrain: "imagenet"
patch_size: "32"
device: "cuda"

im_path_same: "stimuli/patching/10-20/same.png"
im_path_diff: "stimuli/patching/10-20/different.png"
im_path_corrupt: "stimuli/patching/10-20/texture.png"


outpath: "Results/Patching/Imagent/10-20/texture"